//! `.npy` reference-vector loader.
//!
//! Reference vectors generated by `tools/oracle-gen/` are committed to
//! `tests/vectors/` in numpy's `.npy` binary format. This module loads them
//! into native Rust slices for use by tests.
//!
//! # Phase 0 status
//!
//! Stub. The loader signatures below define the shape of the API but the
//! implementations are deferred to the first kernel that needs a `.npy`
//! reference vector. The roadmap (`docs/roadmap.md`, "Phase 1 — Tier-1
//! RF/electrical primitives") expects this to happen at the Hann window
//! step.
//!
//! When implemented, the loader should:
//!
//! - Parse the `.npy` v1.0/v2.0/v3.0 header (a small dict literal in ASCII).
//! - Verify the `dtype` and `shape` match what the caller expects.
//! - Return a borrowed slice or owned `Vec`, picking the form that avoids
//!   re-allocation on the hot path.
//! - Refuse `.npy` files saved with `allow_pickle = True` (security
//!   defence-in-depth, though numpy stopped defaulting that to True years
//!   ago).
//!
//! A pure-Rust implementation is preferable to a binding. The format is
//! small enough that hand-rolling is easy and avoids a dependency.

use std::path::Path;

use num_complex::Complex;

/// Load a `.npy` file containing a 1-D array of `f32` values.
///
/// # Panics
///
/// Stub: always panics.
#[must_use]
pub fn load_f32(_path: &Path) -> Vec<f32> {
    unimplemented!(
        "honeyeater_test::npy::load_f32 is a Phase 0 stub; \
         implementation deferred to first kernel that needs a .npy reference vector"
    );
}

/// Load a `.npy` file containing a 1-D array of `f64` values.
///
/// # Panics
///
/// Stub: always panics.
#[must_use]
pub fn load_f64(path: &Path) -> Vec<f64> {
    let bytes = std::fs::read(path).expect("Failed to read .npy file");

    let npy_reader = npyz::NpyFile::new(&bytes[..]).expect("Failed to parse .npy file");
    npy_reader
        .data::<f64>()
        .expect("Failed to read .npy data")
        .map(|value| value.expect("Failed to parse individual floating point values"))
        .collect()
}

/// Load a `.npy` file containing a 1-D array of `Complex<f32>` values.
///
/// numpy stores complex arrays as interleaved real/imaginary pairs, which
/// is the same memory layout as a slice of [`num_complex::Complex<f32>`].
/// The loader returns the data in honeyeater's preferred type to avoid a
/// caller-side cast on every test.
///
/// # Panics
///
/// Stub: always panics.
#[must_use]
pub fn load_complex_f32(_path: &Path) -> Vec<Complex<f32>> {
    unimplemented!(
        "honeyeater_test::npy::load_complex_f32 is a Phase 0 stub; \
         implementation deferred to first kernel that needs a .npy reference vector"
    );
}

/// Load a `.npy` file containing a 1-D array of `Complex<f64>` values.
///
/// # Panics
///
/// Stub: always panics.
#[must_use]
pub fn load_complex_f64(_path: &Path) -> Vec<Complex<f64>> {
    unimplemented!(
        "honeyeater_test::npy::load_complex_f64 is a Phase 0 stub; \
         implementation deferred to first kernel that needs a .npy reference vector"
    );
}
