//! `.npy` reference-vector loader.
//!
//! Reference vectors generated by `tools/oracle-gen/` are committed to
//! `tests/vectors/` in numpy's `.npy` binary format. This module loads them
//! into native Rust slices for use by tests.
//!
//! # Phase 0 status
//!
//! Implemented. Reference vectors are loaded using `npyz`, with validation
//! that arrays are one-dimensional and do not contain pickled/object data.

use std::error::Error;
use std::fs::File;
use std::io::{BufReader, Error as IoError, ErrorKind};
use std::path::Path;

use num_complex::Complex;

pub type NpyResult<T> = Result<T, Box<dyn Error>>;

/// Generic 1-Dimensional Loader
fn load_1d<T>(path: &Path) -> NpyResult<Vec<T>>
where
    T: npyz::Deserialize,
{
    // Open the file without reading the whole thing into memory first.
    let file = File::open(path)?;
    let reader = BufReader::new(file);

    // Parse the .npy header.
    let npy = npyz::NpyFile::new(reader)?;

    // Honeyeater's loader contract is specifically for 1-D reference vectors.
    if npy.shape().len() != 1 {
        return Err(IoError::new(
            ErrorKind::InvalidData,
            format!("expected a 1-D .npy array, found shape {:?}", npy.shape()),
        )
        .into());
    }

    // Never allow Python pickle/object arrays.
    if npy.uses_pickled_array() {
        return Err(IoError::new(
            ErrorKind::InvalidData,
            "pickled/object .npy arrays are not supported",
        )
        .into());
    }

    // npyz checks that the numpy dtype is compatible with T.
    let data: Vec<T> = npy.into_vec()?;

    Ok(data)
}
/// Load a `.npy` file containing a 1-D array of `f32` values.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, is not a valid `.npy` file,
/// is not one-dimensional, contains pickled/object data, or has a dtype that
/// cannot be deserialised as `f32`.
#[must_use]
pub fn load_f32(path: &Path) -> NpyResult<Vec<f32>> {
    load_1d(path)
}

/// Load a `.npy` file containing a 1-D array of `f64` values.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, is not a valid `.npy` file,
/// is not one-dimensional, contains pickled/object data, or has a dtype that
/// cannot be deserialised as `f64`.
#[must_use]
pub fn load_f64(path: &Path) -> NpyResult<Vec<f64>> {
    load_1d(path)
}

/// Load a `.npy` file containing a 1-D array of `Complex<f32>` values.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, is not a valid `.npy` file,
/// is not one-dimensional, contains pickled/object data, or has a dtype that
/// cannot be deserialised as `Complex<f32>`.
#[must_use]
pub fn load_complex_f32(path: &Path) -> NpyResult<Vec<Complex<f32>>> {
    load_1d(path)
}

/// Load a `.npy` file containing a 1-D array of `Complex<f64>` values.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, is not a valid `.npy` file,
/// is not one-dimensional, contains pickled/object data, or has a dtype that
/// cannot be deserialised as `Complex<f64>`.
#[must_use]
pub fn load_complex_f64(path: &Path) -> NpyResult<Vec<Complex<f64>>> {
    load_1d(path)
}

/// Load a `.npy` file containing a 1-D array of `Complex<i32>` values.
///
/// # Errors
///
/// Returns an error if the file cannot be opened, is not a valid `.npy` file,
/// is not one-dimensional, contains pickled/object data, or has a dtype that
/// cannot be deserialised as `Complex<i32>`.
#[must_use]
pub fn load_complex_i32(path: &Path) -> NpyResult<Vec<Complex<i32>>> {
    let flat_data: Vec<i32> = load_1d(path)?;

    if flat_data.len() % 2 != 0 {
        return Err(IoError::new(
            ErrorKind::InvalidData,
            "complex i32 vector must contain an even number of interleaved values",
        )
        .into());
    }

    Ok(flat_data
        .chunks_exact(2)
        .map(|chunk| Complex::new(chunk[0], chunk[1]))
        .collect())
}
